// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Rise.ReportCore;

namespace Rise.ReportCore.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20220206082620_Report_20220206")]
    partial class Report_20220206
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 63)
                .HasAnnotation("ProductVersion", "5.0.13")
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

            modelBuilder.Entity("Rise.ReportCore.Models.Const", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("CDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ConstDesc")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("ConstID")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<int?>("ConstOrder")
                        .HasColumnType("integer");

                    b.Property<string>("ConstValue")
                        .HasColumnType("text");

                    b.Property<bool?>("Deleted")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("MDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ConstID", "ConstValue")
                        .IsUnique();

                    b.ToTable("Consts");

                    b.HasData(
                        new
                        {
                            Id = new Guid("069049d0-0093-43be-b284-ee1e28a8af7a"),
                            CDate = new DateTimeOffset(new DateTime(2022, 2, 6, 11, 26, 20, 359, DateTimeKind.Unspecified).AddTicks(4500), new TimeSpan(0, 3, 0, 0, 0)),
                            ConstDesc = "Cell Phone",
                            ConstID = "ReportInfoTypes",
                            ConstOrder = 0,
                            ConstValue = "0",
                            Deleted = false
                        },
                        new
                        {
                            Id = new Guid("291166bb-6a69-47e5-ac68-da1c96cc78b6"),
                            CDate = new DateTimeOffset(new DateTime(2022, 2, 6, 11, 26, 20, 359, DateTimeKind.Unspecified).AddTicks(5711), new TimeSpan(0, 3, 0, 0, 0)),
                            ConstDesc = "E-Mail",
                            ConstID = "ReportInfoTypes",
                            ConstOrder = 1,
                            ConstValue = "1",
                            Deleted = false
                        },
                        new
                        {
                            Id = new Guid("f02fb45c-a0fe-485c-8b3e-b91734afc1c8"),
                            CDate = new DateTimeOffset(new DateTime(2022, 2, 6, 11, 26, 20, 359, DateTimeKind.Unspecified).AddTicks(5726), new TimeSpan(0, 3, 0, 0, 0)),
                            ConstDesc = "Location",
                            ConstID = "ReportInfoTypes",
                            ConstOrder = 2,
                            ConstValue = "2",
                            Deleted = false
                        },
                        new
                        {
                            Id = new Guid("8865d315-2662-4f7f-bb13-123826efb599"),
                            CDate = new DateTimeOffset(new DateTime(2022, 2, 6, 11, 26, 20, 359, DateTimeKind.Unspecified).AddTicks(5729), new TimeSpan(0, 3, 0, 0, 0)),
                            ConstDesc = "Preparing",
                            ConstID = "ReportStatus",
                            ConstOrder = 0,
                            ConstValue = "0",
                            Deleted = false
                        },
                        new
                        {
                            Id = new Guid("a9481bcf-79f1-4cad-9ae3-26e7b53a931a"),
                            CDate = new DateTimeOffset(new DateTime(2022, 2, 6, 11, 26, 20, 359, DateTimeKind.Unspecified).AddTicks(5732), new TimeSpan(0, 3, 0, 0, 0)),
                            ConstDesc = "Completed",
                            ConstID = "ReportStatus",
                            ConstOrder = 1,
                            ConstValue = "1",
                            Deleted = false
                        });
                });

            modelBuilder.Entity("Rise.ReportCore.Models.ConstLang", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("CDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ConstLangDesc")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid>("ConstRID")
                        .HasColumnType("uuid");

                    b.Property<bool?>("Deleted")
                        .HasColumnType("boolean");

                    b.Property<string>("LangID")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("MDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ConstRID");

                    b.ToTable("ConstLangs");
                });

            modelBuilder.Entity("Rise.ReportCore.Models.Report", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("CDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool?>("Deleted")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("MDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ReportID")
                        .HasColumnType("text");

                    b.Property<string>("ReportName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.ToTable("Reports");

                    b.HasData(
                        new
                        {
                            Id = new Guid("4ee62dab-c72b-4a97-9e5c-12a519b2ffd3"),
                            CDate = new DateTimeOffset(new DateTime(2022, 2, 6, 11, 26, 20, 343, DateTimeKind.Unspecified).AddTicks(6924), new TimeSpan(0, 3, 0, 0, 0)),
                            Deleted = false,
                            ReportID = "00001",
                            ReportName = "Statistics of Contact by Location"
                        });
                });

            modelBuilder.Entity("Rise.ReportCore.Models.ReportRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("CDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool?>("Deleted")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("MDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ReportFilePath")
                        .HasColumnType("text");

                    b.Property<Guid>("ReportRID")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ReportStatusRID")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("RequestedDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ReportRID");

                    b.HasIndex("ReportStatusRID");

                    b.ToTable("ReportRequests");
                });

            modelBuilder.Entity("Rise.ReportCore.Models.ConstLang", b =>
                {
                    b.HasOne("Rise.ReportCore.Models.Const", "Const")
                        .WithMany("ConstLangs")
                        .HasForeignKey("ConstRID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Const");
                });

            modelBuilder.Entity("Rise.ReportCore.Models.ReportRequest", b =>
                {
                    b.HasOne("Rise.ReportCore.Models.Report", "Report")
                        .WithMany("ReportRequests")
                        .HasForeignKey("ReportRID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Rise.ReportCore.Models.Const", "ConstReportStatus")
                        .WithMany("ReportRequests")
                        .HasForeignKey("ReportStatusRID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ConstReportStatus");

                    b.Navigation("Report");
                });

            modelBuilder.Entity("Rise.ReportCore.Models.Const", b =>
                {
                    b.Navigation("ConstLangs");

                    b.Navigation("ReportRequests");
                });

            modelBuilder.Entity("Rise.ReportCore.Models.Report", b =>
                {
                    b.Navigation("ReportRequests");
                });
#pragma warning restore 612, 618
        }
    }
}
